### ISSUE TITLE
try caching

### ISSUE THREAD

**Issue by meoyawn** [infotech-group/android-drawable-dsl#5]
```yaml
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
```
